# Generated by Django 4.2.4 on 2023-09-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suser',
            name='age',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
