# Generated by Django 4.2.4 on 2023-09-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_suser_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suser',
            old_name='addres',
            new_name='address',
        ),
    ]
