# Generated by Django 4.2.4 on 2023-09-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_addres_suser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='suser',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
