# Generated by Django 4.2.4 on 2023-09-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_suser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suser',
            name='img',
            field=models.FileField(blank=True, default='avatar.jpeg', null=True, upload_to='avatar'),
        ),
    ]
