# Generated by Django 4.2.4 on 2023-09-27 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_suser_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
