# Generated by Django 4.2.4 on 2023-09-27 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('postdate', models.DateField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uploadphpto')),
                ('suser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.suser')),
            ],
        ),
    ]
